server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_room
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-aliases-package: com.kerry.smartconferenceroom.entity